package br.com.gestaonumerario.api.core.domain.enums;

public enum EventoHistoricoSolicitacao {
    SOLICITACAO_CRIADA,
    SOLICITACAO_APROVADA,
    SOLICITACAO_REJEITADA,
    SOLICITACAO_CANCELADA,
    ORIGEM_DESTINO_DEFINIDOS,
    OPERACAO_PROGRAMADA,
    SEPARACAO_INICIADA,
    NUMERARIO_EXPEDIDO,
    NUMERARIO_RECEBIDO,
    DIVERGENCIA_REGISTRADA,
    DIVERGENCIA_CONCILIADA,
    OCORRENCIA_REGISTRADA,
    SOLICITACAO_CONCLUIDA,
    SOLICITACAO_CRIADA_LEGADO,
    SOLICITACAO_APROVADA_LEGADO,
    SOLICITACAO_REJEITADA_LEGADO,
    SOLICITACAO_CONCLUIDA_LEGADO
}
