spring.application.name=relatorio-numerario
server.port=${RELATORIOS_PORT:8082}
server.address=${RELATORIOS_ADDRESS:127.0.0.1}
server.error.include-message=always
springdoc.api-docs.enabled=${OPENAPI_ENABLED:true}
springdoc.swagger-ui.enabled=${OPENAPI_ENABLED:true}
