spring.application.name=bff-numerario
server.port=8080
api-numerario.base-url=http://localhost:8081
api-numerario.connect-timeout=3s
api-numerario.read-timeout=10s
relatorios.base-url=${RELATORIOS_BASE_URL:http://localhost:8082}
relatorios.connect-timeout=${RELATORIOS_CONNECT_TIMEOUT:3s}
relatorios.read-timeout=${RELATORIOS_READ_TIMEOUT:60s}
springdoc.api-docs.enabled=${OPENAPI_ENABLED:true}
springdoc.swagger-ui.enabled=${OPENAPI_ENABLED:true}
